# Generated by Django 4.1.7 on 2023-04-02 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("basic_app", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserProfileInfo",
        ),
    ]
